import { Link } from "react-router-dom";
import { Logo } from "@/components/Logo";
import { ArrowLeft } from "lucide-react";

const PrivacyPolicy = () => (
  <div className="mx-auto max-w-3xl px-5 py-12">
    <Link to="/" className="mb-8 inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground">
      <ArrowLeft className="h-4 w-4" /> Back
    </Link>
    <Logo />
    <h1 className="mt-8 font-display text-4xl">Privacy Policy</h1>
    <p className="mt-2 text-sm text-muted-foreground">Last updated: {new Date().toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" })}</p>

    <div className="mt-8 space-y-6 text-sm leading-relaxed text-foreground/85">
      <section>
        <h2 className="font-display text-xl">1. Information We Collect</h2>
        <p className="mt-2">Somion collects the following categories of information:</p>
        <ul className="mt-2 list-disc space-y-1 pl-5">
          <li><strong>Account information:</strong> Email address and password when you create an account.</li>
          <li><strong>Health and fitness data:</strong> Sleep scores, readiness scores, heart rate variability (HRV), resting heart rate, sleep duration, and temperature data imported from your Oura Ring via the Oura API with your explicit consent.</li>
          <li><strong>Self-reported data:</strong> Soreness, energy, and motivation ratings you provide in morning check-ins, along with optional notes.</li>
          <li><strong>Workout data:</strong> Training sessions generated by the app, completion status, and exercise history.</li>
          <li><strong>Profile preferences:</strong> Training goals, experience level, equipment access, coaching tone, and notification preferences.</li>
        </ul>
      </section>

      <section>
        <h2 className="font-display text-xl">2. How We Use Your Information</h2>
        <ul className="mt-2 list-disc space-y-1 pl-5">
          <li>Generate personalized daily workout recommendations based on your recovery state.</li>
          <li>Track your training history and consistency over time.</li>
          <li>Improve the accuracy and relevance of recommendations.</li>
          <li>Communicate with you about your account and the service.</li>
        </ul>
      </section>

      <section>
        <h2 className="font-display text-xl">3. Data Storage and Security</h2>
        <p className="mt-2">Your data is stored securely using Supabase, which provides encryption at rest and in transit. Oura personal access tokens are stored server-side and are never exposed to the browser or app client. We use row-level security policies to ensure users can only access their own data.</p>
      </section>

      <section>
        <h2 className="font-display text-xl">4. Third-Party Services</h2>
        <ul className="mt-2 list-disc space-y-1 pl-5">
          <li><strong>Oura:</strong> We connect to the Oura API to import your health metrics. Somion accesses only the data categories you authorize. You can disconnect Oura at any time in Settings.</li>
          <li><strong>Supabase:</strong> Database and authentication provider. <a href="https://supabase.com/privacy" className="text-primary hover:underline" target="_blank" rel="noreferrer">Supabase Privacy Policy</a></li>
        </ul>
      </section>

      <section>
        <h2 className="font-display text-xl">5. Data Sharing</h2>
        <p className="mt-2">We do not sell, rent, or share your personal data with third parties for marketing purposes. We may share data only:</p>
        <ul className="mt-2 list-disc space-y-1 pl-5">
          <li>With service providers necessary to operate the app (Supabase, hosting).</li>
          <li>When required by law or to protect our legal rights.</li>
          <li>With your explicit consent.</li>
        </ul>
      </section>

      <section>
        <h2 className="font-display text-xl">6. Data Retention and Deletion</h2>
        <p className="mt-2">Your data is retained as long as your account is active. You can request deletion of your account and all associated data by contacting us at <a href="mailto:privacy@somion.app" className="text-primary hover:underline">privacy@somion.app</a>. Upon request, we will delete your data within 30 days, except where retention is required by law.</p>
      </section>

      <section>
        <h2 className="font-display text-xl">7. Your Rights</h2>
        <p className="mt-2">Depending on your jurisdiction, you may have the right to:</p>
        <ul className="mt-2 list-disc space-y-1 pl-5">
          <li>Access the personal data we hold about you.</li>
          <li>Request correction of inaccurate data.</li>
          <li>Request deletion of your data.</li>
          <li>Object to or restrict processing of your data.</li>
          <li>Export your data in a portable format.</li>
        </ul>
        <p className="mt-2">To exercise these rights, contact <a href="mailto:privacy@somion.app" className="text-primary hover:underline">privacy@somion.app</a>.</p>
      </section>

      <section>
        <h2 className="font-display text-xl">8. Children's Privacy</h2>
        <p className="mt-2">Somion is not intended for use by anyone under the age of 16. We do not knowingly collect personal information from children.</p>
      </section>

      <section>
        <h2 className="font-display text-xl">9. Changes to This Policy</h2>
        <p className="mt-2">We may update this Privacy Policy from time to time. We will notify you of material changes by posting the updated policy within the app.</p>
      </section>

      <section>
        <h2 className="font-display text-xl">10. Contact</h2>
        <p className="mt-2">For questions or concerns about this Privacy Policy, contact us at <a href="mailto:privacy@somion.app" className="text-primary hover:underline">privacy@somion.app</a>.</p>
      </section>
    </div>
  </div>
);

export default PrivacyPolicy;
